language: java
jdk:
- oraclejdk8
dist: trusty

services:
  - docker

install:
  - docker build -t firebird .

jobs:
  include:
    - stage: Test
      script: gradle test


script:
  - "cd source"
  - chmod 777 travis.sh
  - ./travis.sh
  - "gradle test"
