language: java
jdk:
- oraclejdk8
dist: trusty

services:
  - docker


#jobs:
#  include:
#    - stage: Test
#      script: gradle test


script:
  - "cd source"
  - chmod 777 travis.sh
  - travis.sh
  - docker build -t firebird .
  - "gradle test"
